all:
  children:

    swarm_manager:
      hosts:
        tools.diesel.net:
        
  vars:
    storage_retention: 1y
    
    kiwi_host: loki.kiwi-labs.net
    diesel_host: loki.diesel.net

    # encrypted SHA htpasswd (user:password)
    loki_htpasswd: "{{ lookup('env', 'LOKI_HTPASSWD') }}"
    
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
