kind: pipeline
type: docker
name: Build Grafana Loki

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  - name: deploy
    image: plugins/ansible:3
    environment:
      LOKI_HTPASSWD:
        from_secret: loki_htpasswd
    settings:
      inventory: .ansible/inventories/production
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
trigger:
  branch:
    - development
  event:
    - push

...
