- hosts: swarm_manager
  roles:
    - application
    - traefik
  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir

    - include_role:
        name: application
        tasks_from: make_data_dir

    # https://github.com/grafana/loki/issues/2018
    - file:
        path: '{{ data_dir }}'
        owner: '10001'
        group: '10001'
        mode: u=rwx
      become: yes

    - name: 'render loki-config.yaml to loki-config.yaml'
      template:
        src: loki-config.yaml
        dest: '{{ config_dir }}/loki-config.yaml'
        
    - include_role:
        name: docker
        tasks_from: stack_deploy

    - include_role:
        name: docker
        tasks_from: service_update
      vars:
        options: --force
        docker_service: loki
